os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
build_platform:
  linux_aarch64: linux_aarch64
bot:
  abi_migration_branches:
  - qt6
